-- Insert example marketplace listings for Pittsburgh, PA
INSERT INTO public.marketplace_listings (
  category,
  title,
  description,
  price,
  contact_email,
  contact_phone,
  website_url,
  location_address,
  location_city,
  location_state,
  location_country,
  location_latitude,
  location_longitude,
  status,
  subscription_status,
  subscription_end,
  user_id
) VALUES
  -- Example Vendor (Contractor)
  (
    'vendor',
    'Steel City Home Renovations',
    'Professional home renovation and remodeling services in the Pittsburgh area. Specializing in kitchen remodels, bathroom upgrades, basement finishing, and whole-home renovations. Licensed and insured with over 15 years of experience. We pride ourselves on quality craftsmanship, transparent pricing, and completing projects on time and within budget.',
    NULL,
    'info@steelcityrenovations.com',
    '(412) 555-1234',
    'https://www.housebudgetcalculator.com/compare-prices',
    'Pittsburgh, PA',
    'Pittsburgh',
    'PA',
    'United States',
    40.4406,
    -79.9959,
    'active',
    'active',
    '2026-10-02',
    '00000000-0000-0000-0000-000000000000'
  ),
  -- Example Vacation Rental
  (
    'vacation',
    'Downtown Pittsburgh Loft',
    'Beautiful 2-bedroom loft in the heart of downtown Pittsburgh with stunning city views. Walking distance to PNC Park, Heinz Field, and the Cultural District. Perfect for families or groups visiting the city. Fully equipped kitchen, high-speed WiFi, and free parking included. Sleeps 6 comfortably. Minimum 2-night stay. Experience Pittsburgh like a local!',
    150.00,
    'bookings@pittsburghloft.com',
    '(412) 555-5678',
    'https://www.housebudgetcalculator.com/vacation',
    'Pittsburgh, PA',
    'Pittsburgh',
    'PA',
    'United States',
    40.4406,
    -79.9959,
    'active',
    'active',
    '2026-10-02',
    '00000000-0000-0000-0000-000000000000'
  ),
  -- Example Handmade Gift
  (
    'gift',
    'Three Rivers Handcrafted Jewelry',
    'Unique handcrafted jewelry inspired by Pittsburgh''s three rivers. Each piece is carefully designed and made with love using high-quality materials including sterling silver, copper, and locally-sourced gemstones. Perfect for gifts or treating yourself! Custom orders available. Featured items include river-themed pendants, Pittsburgh bridge earrings, and skyline bracelets. All pieces come with a certificate of authenticity.',
    45.00,
    'shop@threeriversjewelry.com',
    '(412) 555-9012',
    'https://www.housebudgetcalculator.com/gifts',
    'Pittsburgh, PA',
    'Pittsburgh',
    'PA',
    'United States',
    40.4406,
    -79.9959,
    'active',
    'active',
    '2026-10-02',
    '00000000-0000-0000-0000-000000000000'
  );